version: "2"
services:
  test:
    build:
      args:
        - SKIP_TEST
      context: .
      dockerfile: git-custom-commands-test/Dockerfile
    volumes:
      - ./git-custom-commands-test:/test
      - ./bin/git-review:/usr/bin/git-review
      - ./bin/git-review.py:/usr/bin/git-review.py
      - ./bin/git-submit:/usr/bin/git-submit
      - ./bin/git-submit.py:/usr/bin/git-submit.py
  test-hooks:
    build:
      context: .
      dockerfile: git-hooks-test/Dockerfile
    volumes:
      - ./git-hooks-test:/test
      - ./hooks:/usr/share/hooks
  test-reviewable:
    build:
      context: reviewable
      dockerfile: Dockerfile
    volumes:
      - ./reviewable/.eslintrc.json:/usr/src/app/.eslintrc.json:ro
      - ./reviewable/lgtm_plus_resolved_discussions.js:/usr/src/app/lgtm_plus_resolved_discussions.js:ro
      - ./reviewable/test:/usr/src/app/test:ro
