version: "2"
services:
  test:
    build:
      context: .
      dockerfile: git-custom-commands-test/Dockerfile
    volumes:
      - ./git-custom-commands-test:/test
  test-reviewable:
    build:
      context: reviewable
      dockerfile: Dockerfile
    volumes:
      - ./reviewable/.eslintrc.json:/usr/src/app/.eslintrc.json:ro
      - ./reviewable/lgtm_plus_resolved_discussions.js:/usr/src/app/lgtm_plus_resolved_discussions.js:ro
      - ./reviewable/test:/usr/src/app/test:ro
