version: "2"
services:
  test:
    build:
      context: .
      dockerfile: git-custom-commands-test/Dockerfile
    volumes:
      - ./git-custom-commands-test:/test
  test-reviewable:
    build:
      context: reviewable
      dockerfile: Dockerfile
