#!/usr/bin/env bash
#
# bash completion support for git-rebase-last

_git_rebase_last()
{
  __git_complete_refs
  if [[ "$cur" == "-"* ]]; then
    __gitcompappend "--onto"
  fi
}

complete -F __git_complete_refs git-rebase-last
