#!/bin/bash
#
# Check the staged changes before committing them.

. "$(git --exec-path)/git-sh-setup"  # for die
readonly CIRCLE_CI_CONFIG="$(git rev-parse --show-toplevel)/.circleci/config.yml"

if [ -f "$CIRCLE_CI_CONFIG" ]; then
  if ! command -v circleci > /dev/null && [ -z "$PRECOMMIT_NO_CIRCLECI_WARNING" ]; then
    echo "It looks like you're using CircleCI,
      but its configuration validating tool is not installed."
    echo "To check configuration changes before committing them, please run 'npm -g i circleci'."
    echo "To avoid showing this message again, please set 'PRECOMMIT_NO_CIRCLECI_WARNING=1'"
    exit
  fi
  # Validate the Circle CI config, if it changed.
  git diff-index --quiet -p -M HEAD -- "$CIRCLE_CI_CONFIG" ||
    circleci config validate "$CIRCLE_CI_CONFIG" > /dev/null ||
    die "CircleCI config is not valid."
fi
