.TH GIT-SUBMIT 1 "24 February 2016" "1.0" "Git Manual"
.SH NAME
git-submit \- submit the given or the current branch
.SH SYNOPSIS
\fIgit submit\fR [BRANCH]
.SH DESCRIPTION
git-submit rebases a branch on top of master before pushing master to the tracked remote. It does the equivalent of a merge of a pull request on GitHub but by rebasing so keeping a clean history.
.SH OPTIONS
.TP
.BR \-a ", " \-\-abort\fR
Recreate a branch from origin, without the username prefix.
Will also cancel any auto-submission in a future release.
.TP
.BR \-f ", " \-\-force\fR
Forces the submit, disregarding the CI status.
.TP
.BR \-u ", " \-\-user = USER\fR
Set the prefix for the remote branch to USER. Default is username from the git user's email (such as in username@example.com). Only useful for
.ul 1
--abort
.SH SEE ALSO
\fBgit-merge\fR(1), \fBgit-commit\fR(1), \fBgit-push\fR(1)
.SH AUTHOR
Pascal Corpet (pascal@corpet.net)
.SH GIT
Extends the \fBgit\fR(1) suite
